spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

logging:
  level:
    com.testautomation.orchestrator: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

# Disable async for tests
spring:
  task:
    execution:
      pool:
        core-size: 1
        max-size: 1