spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.testautomation.orchestrator: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

# GitLab configuration
gitlab:
  base-url: https://gitlab.com
  mock-mode: false  # Set to true for development/testing without real GitLab
  timeout: 60
  max-retries: 3

# Scheduling Configuration
scheduling:
  token-validation:
    # Cron expression for token validation job (default: every day at 2:00 AM)
    # Format: second minute hour day month weekday
    # 0 0 2 * * * = Every day at 2:00 AM
    cron: ${TOKEN_VALIDATION_CRON:0 0 2 * * *}
  pipeline-status:
    # Pipeline status polling interval in milliseconds (default: 60 seconds)
    polling-interval: ${PIPELINE_STATUS_POLLING_INTERVAL:60000}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/pipeline_orchestrator}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    com.testautomation.orchestrator: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN